server.port=8090

spring.datasource.url=jdbc:postgresql://your-supabase-url:5432/postgres
spring.datasource.username=postgres.nobtbzvsqvkslmuurdog
spring.datasource.password=2wpTiuOOtPzvZH0a
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

# AWS \uD0A4 \uC2E4\uC81C\uAC12 \u2192 \uB354\uBBF8\uAC12\uC73C\uB85C \uAD50\uCCB4!
spring.cloud.aws.credentials.accessKey=your-access-key
spring.cloud.aws.credentials.secretKey=your-secret-key
spring.cloud.aws.s3.bucket=your-bucket-name
spring.cloud.aws.region.static=ap-northeast-2